### PR TITLE
Add read-only open support.

### PR DESCRIPTION
**Pull request by vbatoufflet**
Hi,

I added a basic `read-only` open support for Whisper databases files by separating opening functions.

It implements both `Open` and `OpenFile` methods as used in the `os` package. 

Could you please take a look at this pull request and let me know if it suits to you?

Best regards,
## 

Vincent Batoufflet

### CODE REVIEW

**Comment by kisielk** [comment]
Open needs to be able to open the file for writing, otherwise this breaks existing code that uses it and assumes it will be able to write.

It would probably be useful to provide a method that lets you operate on a whisper database from an io.ReadWriteSeeker instead.

**Comment by vbatoufflet** [comment]
Hi Kamil,

Thank you for your quick response.

To be honest, I just assumed that if the `os.ErrPermission` was triggered when trying to use `Write` it will be almost the same behavior (as it generates an error) than triggering it when opening, preventing the library from reading meta-data and/or archives information.

I ran the tests and as it used `Create` I didn't encounter error. But indeed, I agree that it will trigger an `os.ErrPermission` when trying to update or set aggregation.

I will try to think on something more suitable, which could allows this package to open Whisper databases read-only.

Regards.

**Comment by kisielk** [comment]
I think if openWhisper was made exported (and maybe renamed to NewWhisper or something), and the first argument was an io.ReadWriteSeeker then you could open the file outside and just pass it in to that function. It would probably require additional refactoring in other parts of the code.

**Comment by vbatoufflet** [comment]
Sure, it could be definitely do the trick.

To figure a way to implement such a change, do you think of a global replacement of the `file` field in the `Whisper` struct by an `io.ReadWriteSeeker` and a refactoring of code relying on it?

If so, and if this change allows us to open the file prior to call `NewWhisper`, the developer will be responsible of closing the file, but what about a call `Close` method not having an `os.File` anymore?

**Comment by kisielk** [comment]
I actually prototyped the code this afternoon. Will send as a PR on a separate branch so you can have a look.

**Comment by vbatoufflet** [comment]
Great news. Thanks for having taking the time to look at it.

**Comment by kisielk** [comment]
The change is actually quite simple. If it seems suitable all that would be left is to export OpenWhisper and add some documentation.

**Comment by Dieterbe** [comment]
this is a little confusing

```
func Open

func Open(path string) (*Whisper, error)

Open opens an existing whisper database. It returns an error if the file does not exist or is not a valid whisper archive.
func OpenWhisper

func OpenWhisper(f io.ReadWriteSeeker) (*Whisper, error)

OpenWhisper opens an existing Whisper database from the given ReadWriteSeeker. 
```

so what do we have to do to open whisper files in read only mode?
the included whisper-info, whisper-dump and whisper-fetch tools still use Open which results in `permission denied` because i have only read permissions. might want to fix those.
I could do the PR, except i don't understand how i'm supposed to open in read only mode

**Comment by kisielk** [comment]
@Dieterbe you should be able to os.Open the file and pass it in to OpenWhisper

**Pull request closed without merging**
